default_config:
logger:
  default: info
  logs:
    homeassistant: info
    homeassistant.components: warning
system_log:
  fire_event: true
recorder:
  purge_keep_days: 10
  db_url: sqlite:////config/home-assistant_v2.db
history:
logbook:
sun:
system_health:
frontend:
config:
mobile_app:
zeroconf:
homeassistant:
  name: Coruscant
  latitude: 34.05
  longitude: -118.24
  elevation: 71
  unit_system: us_customary
  time_zone: __TIME_ZONE__
  external_url: https://__EXTERNAL_DOMAIN__
  internal_url: https://__EXTERNAL_DOMAIN__
input_boolean:
  washer_battery_alerted:
    name: "Washer Battery Low Alerted"
    initial: off
template:
  - binary_sensor:
      - name: "Washer Cleaning State"
        state: >
          {{ is_state('binary_sensor.washer_vibration', 'on') }}

        delay_off:
          minutes: 10
        delay_on:
          seconds: 20
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
script: !include_dir_merge_named scripts/
scene: !include_dir_merge_list scenes/
