wpa-supplicant: ENC[AES256_GCM,data:KCj+DLcn0CmxsvKx1Cgv9rA78pAbUVMR9ch59YibQyrX2eBWpR3icd+nghJ8ZVWjSaE1czbOYQvyYWUZYJAM,iv:Ocm7VxkmdjyPR2cLGO4XbLLwAE4ne1czuOk7SYcsPJw=,tag:ghRgEH94WbJQGm8KQC/5nA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK0Q4eXR5Z0tmb0ZuTTRS
        dFVvNGNJNmdIQTJKTE4rMEZycXhLYi9sdlJVCmFtY3UrZDkxUnRWd05pOUJEeUY2
        VHh2bml3N2FyYUFraFo5ajRwS3N1b1EKLS0tIHptZ1lUU1MyNDZycWtBZEVXNG1R
        YWRzUm1vaFIzSzhYK2p5Yng5QWlZL2sKwGP10ZZNNwi2Wmczwe8WyTU3GpW4eEcR
        536x77ivwsyR8dPGknUm/sTGQgxuzAmho1A4waIkQ71rnx1SPneMlw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sgfy6dm4jg72eqx2rw0003cxrt8rkr6q0pp395djh99jwsulw52sc5pv7l
  lastmodified: "2026-06-06T22:19:29Z"
  mac: ENC[AES256_GCM,data:fs01wDyKozEnFGDTHrzRH6VGNfaz6+G8g6obRmg6xHYeOJEqzWwBkwj2ro5XOe6B4fzrbokW6OI3znMJNhbSMdj5sMDSbmV6+IFjs9EafUhsR2S322YW1GmKaM3wV/QAsYioHQ4/s+4eJZZYnrblPnRgIzW/VynUsS52juu/ltI=,iv:GwOWAK+2anzFcIaQC+mOpj4dpCiZ5SxWu8b5SW15GHA=,tag:Y2P+v8MBp5glAu/fYwTotw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
