wpa-supplicant: ENC[AES256_GCM,data:7YIH+cqo5HDgDlRlUJMkBzkVpaNORD8zL4TXUVgZK/SmX7HH+n3JVJLaUSw9Fbb1SdT+moJnf5iKGQ==,iv:5gMMWtD4+kTf+fIIeF2PBnnytAvNyyUwy9IpBiUlHZs=,tag:Fo4O/4T2NG100F+miwdiHw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK0Q4eXR5Z0tmb0ZuTTRS
        dFVvNGNJNmdIQTJKTE4rMEZycXhLYi9sdlJVCmFtY3UrZDkxUnRWd05pOUJEeUY2
        VHh2bml3N2FyYUFraFo5ajRwS3N1b1EKLS0tIHptZ1lUU1MyNDZycWtBZEVXNG1R
        YWRzUm1vaFIzSzhYK2p5Yng5QWlZL2sKwGP10ZZNNwi2Wmczwe8WyTU3GpW4eEcR
        536x77ivwsyR8dPGknUm/sTGQgxuzAmho1A4waIkQ71rnx1SPneMlw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sgfy6dm4jg72eqx2rw0003cxrt8rkr6q0pp395djh99jwsulw52sc5pv7l
  lastmodified: "2026-06-06T22:10:57Z"
  mac: ENC[AES256_GCM,data:2nNqOOHCTKwOE86prcKEP7YDM2/gK5OLULXca85kFaAnvIyUigpDLCB+08eemO4SQHj8M0HFNNOBTMb78leBq18xJDNUAkxGei/9WOO8hCj7JGSFlYrurqW9ktihwYI/mDj0zxh77lC0QqzsGIgYpmp+bFywNK58X5CGPKhVFZU=,iv:I3ZIEgqJ9+DyOXD0n0KjEDq+IsEwOQZTlksCNBE13rg=,tag:p2W0i/dUPfY7VdF2W4yXZA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
