wpa-supplicant: ENC[AES256_GCM,data:KCj+DLcn0CmxsvKx1Cgv9rA78pAbUVMR9ch59YibQyrX2eBWpR3icd+nghJ8ZVWjSaE1czbOYQvyYWUZYJAM,iv:Ocm7VxkmdjyPR2cLGO4XbLLwAE4ne1czuOk7SYcsPJw=,tag:ghRgEH94WbJQGm8KQC/5nA==,type:str]
ts-auth-key: ENC[AES256_GCM,data:evznliynV44KEZ01HsxPV5/srUyRIjPXRjBy+dDqjDjuXRsa1boEkjmnsG90SqnlVfPQGFBn2Z0+kDeo7vE=,iv:TRpMpldOPgEdepjM50g1YV86afMuGGAn1NETo4lES4Y=,tag:MsWRUEUmYpUu4aZB8LfGEQ==,type:str]
cloudflare-api-key: ENC[AES256_GCM,data:P0X5CaJbXm2KGK3G3f8RsqOkdVBSw8VVS0efQlGdo0raXBtsaKA++g==,iv:XFTDB4W4PecrMrWeQgu6YO4IwomvNpAppNFGRWZEIg0=,tag:maWs4/ynSEFCgWfikpdxsg==,type:str]
home-assistant-external-domain: ENC[AES256_GCM,data:QxSdk88ecQn6Is77UsbrvXY=,iv:DTDyLpRWwKUzxjWt4RMH5y/dOHXCQ7aC81n3xpTrKOg=,tag:sCu8ZDeLFNp2i6oVZ7JY2w==,type:str]
beszel-domain: ENC[AES256_GCM,data:NvGaLaJMt4Zphft106PvACWZhSfmhIf8TQ==,iv:HzgkiyX6poSI39OQMNtFK+1Tv32gSSkjMYrl15qwznk=,tag:elskpMdwZeH0Bj6P+r6dUQ==,type:str]
lets-encrypt-email: ENC[AES256_GCM,data:I//q1/k4CE1LF7FdcTAMOrwQzLaR2o67rXk=,iv:8CsWm8OENiGcghVMe9jiQAv/EKJpx7dO9rUJHgg9I7s=,tag:9R0EXUjoU+//D5dZstSjYQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK0Q4eXR5Z0tmb0ZuTTRS
        dFVvNGNJNmdIQTJKTE4rMEZycXhLYi9sdlJVCmFtY3UrZDkxUnRWd05pOUJEeUY2
        VHh2bml3N2FyYUFraFo5ajRwS3N1b1EKLS0tIHptZ1lUU1MyNDZycWtBZEVXNG1R
        YWRzUm1vaFIzSzhYK2p5Yng5QWlZL2sKwGP10ZZNNwi2Wmczwe8WyTU3GpW4eEcR
        536x77ivwsyR8dPGknUm/sTGQgxuzAmho1A4waIkQ71rnx1SPneMlw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sgfy6dm4jg72eqx2rw0003cxrt8rkr6q0pp395djh99jwsulw52sc5pv7l
  lastmodified: "2026-06-26T08:28:59Z"
  mac: ENC[AES256_GCM,data:1CH+S0LCH/7HpBbLyL2CsFd29hO+iPSopHGTXX8f7EctRk2oEMNt3xQ/FwLavvMga4zvKSwMo/7N4gqgWXP8oLG3M1WRrb8hEQ5ZQax70vsgcBcDpHdm+sGwtQ9qG8WRDJEpn3MxdI02pf16ce90P8dcXuFF1vZoPYFHN0TBrtg=,iv:dhd27JegNxIFOv9gvH4nho+TZiGaezSZV8a1qWGJAos=,tag:2yjhjAgpyX3UU2P9rK2zJg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
